---
  - name: Install Avocado Packages
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - python3-avocado
      - python3-avocado-plugins-glib
      - python3-avocado-plugins-golang
      - python3-avocado-plugins-loader-yaml
      - python3-avocado-plugins-output-html
      - python3-avocado-plugins-result-upload
      - python3-avocado-plugins-runner-docker
      - python3-avocado-plugins-runner-remote
      - python3-avocado-plugins-runner-vm
      - python3-avocado-plugins-varianter-cit
      - python3-avocado-plugins-varianter-pict
      - python3-avocado-plugins-varianter-yaml-to-mux
    when: ansible_facts['distribution_file_variety'] == "RedHat"
