---
- name: Installs Avocado using RPM packages from the Copr repo
  hosts: avocado-test-deployment
  tasks:
    - include_vars: vars.yml
    - include_tasks: tasks/epel.yml
    - include_tasks: tasks/avocado_copr_repo.yml
    - include_tasks: tasks/avocado_rpm_pkgs.yml
    - name: Avocado version
      shell: "avocado --version"
      changed_when: false
    - include_tasks: tasks/avocado_vt_copr_repo.yml
    - include_tasks: tasks/avocado_vt_rpm_pkg.yml
    - include_tasks: tasks/avocado_vt_rpm_deps.yml
    - include_tasks: tasks/avocado_vt_smoke.yml
